
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:5.4.0
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - ./data/zookeeper/data:/data
      - ./data/zookeeper/datalog:/datalog

  kafka1:
    image: confluentinc/cp-kafka:5.3.0
    hostname: kafka1
    container_name: kafka1
    ports:
      - "19092:19092"
    environment:
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9092,PLAINTEXT_HOST://localhost:19092
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - ./data/kafka1/data:/var/lib/kafka/data
    depends_on:
      - zookeeper

  kafdrop:
    image: obsidiandynamics/kafdrop
    restart: "no"
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka1:9092"
    depends_on:
      - kafka1

  prometheus:
    image: prom/prometheus:v2.9.2
    ports:
      - 9091:9090
    volumes:
      - ./pkg/crm_core/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:10.2.2
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=secret
    volumes:
      - ./pkg/crm_core/grafana/provisioning:/etc/grafana/provisioning
      - ./pkg/crm_core/grafana/dashboards:/var/lib/grafana/dashboards

  auth:
    build:
      context: .
      dockerfile: dockerfile-auth
    container_name: auth-service
    image: auth-service
    depends_on:
      - postgres-auth
      - redis
      - zookeeper

  postgres-auth:
    image: postgres:14-alpine
    container_name: as-auth-db
    restart: always
    environment:
      POSTGRES_DB: auth_service_crm
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - '5432:5432'
    volumes:
      - postgres-auth:/var/lib/postgresql/data

  crm:
    build:
      context: .
      dockerfile: dockerfile-crm
    container_name: crm-service
    image: crm-service
    depends_on:
      - postgres-crm
      - redis

  postgres-crm:
    image: postgres:14-alpine
    container_name: cs-crm-db
    restart: always
    environment:
      POSTGRES_DB: crm_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - '5433:5432'
    volumes:
      - postgres-crm:/var/lib/postgresql/data


  redis:
    image: redis
    ports:
      - '6379:6379'

volumes:
  postgres-auth:
    driver: local
  postgres-crm:
    driver: local