app:
  name: 'crm_core'
  version: '1.0.0'

http:
  port: '8082'
  debugPort: '8084'
  default_read_timeout: 5
  default_write_timeout: 5
  default_shutdown_timeout: 5

log:
  level: 'debug'

gin:
  mode: 'debug'

db:
  pool_max: 2
  host: 'localhost'
  user: 'postgres'
  password: 'postgres'
  name: 'postgres'
  port: 5432

Transport:
  Validate:
    Host: http://127.0.0.1:8081
    Timeout: 5s
  ValidateGrpc:
    Host: localhost:9090
jwt:
  access_private_key: private_key
  access_public_key: private_key
  access_token_expired_in: 60m
  access_token_max_age: 60

  refresh_private_key: private_key
  refresh_public_key: private_key
  refresh_token_expired_in: 1440m
  refresh_token_max_age: 1440